CREATE TABLE IF NOT EXISTS BANK (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS BANK_TO_CLIENT(
    CLIENT_ID VARCHAR(255) NOT NULL,
    BANK_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (BANK_ID, CLIENT_ID));
CREATE TABLE IF NOT EXISTS CLIENT (
    ID VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    NAME VARCHAR(255),
    NUMBER_PHONE VARCHAR(255),
    PASSPORT_NUMBER VARCHAR(255),
    PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS CREDIT (
    ID VARCHAR(255) NOT NULL,
    CREDIT_LIMIT NUMERIC(19,2),
    PERCENT_RATE NUMERIC(19,2),
    BANK_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS CREDIT_OFFER (
    ID VARCHAR(255) NOT NULL,
    SUM_CREDIT NUMERIC(19,2),
    CLIENT_ID VARCHAR(255) NOT NULL,
    CREDIT_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS PLANNED_PAYMENT (
    ID VARCHAR(255) NOT NULL,
    CREDIT_BODY_AMOUNT NUMERIC(19,2),
    CREDIT_PERCENT_AMOUNT NUMERIC(19,2),
    DATE_PAYMENT TIMESTAMP,
    SUM_PAYMENT NUMERIC(19,2),
    CREDIT_OFFER_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID));

ALTER TABLE BANK_TO_CLIENT ADD CONSTRAINT BANKTOCLIENTBANK FOREIGN KEY (BANK_ID) REFERENCES BANK;
ALTER TABLE BANK_TO_CLIENT ADD CONSTRAINT BANKTOCLIENTCLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT;
ALTER TABLE CREDIT ADD CONSTRAINT CREDITBANK FOREIGN KEY (BANK_ID) REFERENCES BANK;
ALTER TABLE CREDIT_OFFER ADD CONSTRAINT CREDITOFFERCLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT;
ALTER TABLE CREDIT_OFFER ADD CONSTRAINT CREDITOFFERCREDIT FOREIGN KEY (CREDIT_ID) REFERENCES CREDIT;
ALTER TABLE PLANNED_PAYMENT ADD CONSTRAINT PLANNEDPAYMENTCREDITOFFER FOREIGN KEY (CREDIT_OFFER_ID) REFERENCES CREDIT_OFFER;
